feat: make rule set a configurable option in cdk-pipelines-step
cdklabs/awscdk-change-analyzer pull request #50
Opened 2021-09-03 23:04 UTC by BryanPan342

2021-09-04 06:54 UTC, BryanPan342 reviewed
TODO:
- [ ] revert some of these changes
- [x] write tests to make sure this works properly

2021-09-04 06:54 UTC, BryanPan342 commented on packages/@aws-c2a/cdk-pipelines-step/test/integ.pipeline-change-analysis.ts
> +          'mv cdk.out ../../../cdk.out',
REVERT THIS BEFORE MERGIN

2021-09-04 06:54 UTC, BryanPan342 commented on packages/aws-c2a/package.json
> +    "aws-sdk": "^2.979.0",
REVERT THIS TOO

2021-09-04 06:54 UTC, BryanPan342 commented on packages/@aws-c2a/cdk-pipelines-step/lib/private/change-analysis-check.ts
> +              'set -e',
Find a way to exit when any of these fail

2021-09-08 12:09 UTC, rix0rrr requested changes

2021-09-08 12:09 UTC, rix0rrr commented on packages/@aws-c2a/cdk-pipelines-step/lib/perform-change-analysis.ts
> +  readonly broadeningPermissions?: boolean;
If we make `ruleSets` an array this could be a predefined set like:

```ts
RuleSet.PREDEF_BROADENING_PERMISSIONS
```

2021-09-09 04:09 UTC, BryanPan342 commented on packages/@aws-c2a/cdk-pipelines-step/README.md
> +      ruleSet: RuleSet.fromDisk(resolve(__dirname, 'rules.json')),
Hmmm i'm still not completely convinced that allowing fo multiple rule sets is the right move. Is there something I'm missing here that would make having multiple rule sets better? 

Having multiple rule sets inherently leads to inefficient scopes and queries...

2021-09-11 01:45 UTC, BryanPan342 commented
@rix0rrr I couldn't get my multiple rule sets to actually run.. I had some code build errors with buildspec that made me very sad.

So i reverted my changes in this branch that got me close to solution thinking I checked out already to a separate branch... buuuuut sadly all of that is lost now :( 

I'm going to merge this one in and add a ticket to support multiple rule sets!

2021-09-11 01:45 UTC, merged